// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAklUV2Uepadpv8ekcBg3g3QtfOVIdk6og',
    appId: '1:1047585846055:web:be0d5539cc67ea86caef02',
    messagingSenderId: '1047585846055',
    projectId: 'f-dilu-fashion-store',
    authDomain: 'f-dilu-fashion-store.firebaseapp.com',
    storageBucket: 'f-dilu-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoNkh-RzVn5PKBXI4ZFf3Yr5xoFESNEGo',
    appId: '1:1047585846055:android:b8d5261c455fded7caef02',
    messagingSenderId: '1047585846055',
    projectId: 'f-dilu-fashion-store',
    storageBucket: 'f-dilu-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3m1LLgSRAzxhcutTXVHzCswt_W8Kdt0Q',
    appId: '1:1047585846055:ios:ef4a9b7660b5ec1bcaef02',
    messagingSenderId: '1047585846055',
    projectId: 'f-dilu-fashion-store',
    storageBucket: 'f-dilu-fashion-store.firebasestorage.app',
    iosBundleId: 'com.kipronodeveloper.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3m1LLgSRAzxhcutTXVHzCswt_W8Kdt0Q',
    appId: '1:1047585846055:ios:ef4a9b7660b5ec1bcaef02',
    messagingSenderId: '1047585846055',
    projectId: 'f-dilu-fashion-store',
    storageBucket: 'f-dilu-fashion-store.firebasestorage.app',
    iosBundleId: 'com.kipronodeveloper.fashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAklUV2Uepadpv8ekcBg3g3QtfOVIdk6og',
    appId: '1:1047585846055:web:35baf1000806ee4bcaef02',
    messagingSenderId: '1047585846055',
    projectId: 'f-dilu-fashion-store',
    authDomain: 'f-dilu-fashion-store.firebaseapp.com',
    storageBucket: 'f-dilu-fashion-store.firebasestorage.app',
  );
}
